### ISSUE TITLE
Body fails when it contains double quotes.

### ISSUE THREAD

**Issue by bjeanes** [meeDamian/github-release#13]
Like https://github.com/meeDamian/github-release/issues/10#issuecomment-562814389, probably need to replace `"` with `\"`. The `sed` filter could probably be moved inline to `toJsonOrNull` to make sure it covers other fields (really just release name).

I know this action is semi-deprecated but I am also stuck on this until the GitHub provided one handles some of the same use cases as your fantastic action.

I'll try to open a PR to fix this but I've worked around it on my end already so unless it comes up again, I _may_ forget, so I thought I'd document it in an issue for the time being.

**Comment by meeDamian** [comment]
Hey, it should be fixed by https://github.com/meeDamian/github-release/commit/5264f5bc3f3ab31750ca5e6b416b27acf83e3187, and I'll tag it as `v2.0.2` soon.

**Comment by stm2** [comment]
Hey, now it fails when the body contains a backslash.
What worked for me
json_escape () {
          printf '%s' "$1" | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))[1:-1]'
}

The python dependency is the downside.
https://stackoverflow.com/questions/10053678/escaping-characters-in-bash-for-json

Actually, could you use jq itself? 
echo $body | jq -R

**Comment by meeDamian** [comment]
@stm2 Can you check if #15 works for you with sth like:

```
uses: meeDamian/github-release@escaping
with:
	…
```

?

**Comment by meeDamian** [comment]
Running a [quick test] in my test repo [produced] this [release], looks good to me.

[quick test]: https://github.com/meeDamian/docker-ci/actions/runs/155457574/workflow#L21-L37
[produced]: https://github.com/meeDamian/docker-ci/runs/830942559?check_suite_focus=true#step:5:20
[release]: https://github.com/meeDamian/docker-ci/releases/tag/v10.10.11

**Comment by stm2** [comment]
Uhm, I think it works as intended, but not for me. It has been a while or I'm beeing stupid. I'd like to do something like
```
jobs:
  build:
    steps:
      - name: Produce body
        run: |
          text=$(echo -e "Hello!\nWorld!\n")
          echo "set-env name=BODY::$text"
      - name: Create release
        uses: meeDamian/github-release@escaping
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG }}
          name: Pre-Release
          body: |
            ${{ env.BODY }}
```
But BODY only contains the first line. How would I go about producing a multiline body like this?
