### ISSUE TITLE
Support cross platform

### ISSUE THREAD

**Issue by AtiqGauri** [meeDamian/github-release#17]
I have windows and macOS specific builds and this action only support linux

Can you introduce cross platform support?

**Comment by meeDamian** [comment]
Could you elaborate a bit?

The action runs in its own Docker container, so I'd need a bit more detail on what's wrong 🤔.

**Comment by AtiqGauri** [comment]
It is giving me error:
`##[error]Container action is only supported on Linux`

![Screenshot_2020-07-20 AtiqGauri atiq_test(2)](https://user-images.githubusercontent.com/37737221/87937564-95891580-cab2-11ea-9a5b-dca0848b1929.png)


Workflow:
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: get release info
        run:   |
              echo ::set-env name=TAG_NAME::$(git describe --tags `git rev-list --tags --max-count=1`)
        shell: bash

      
      - name: release 
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          draft: true
          gzip: false
          files: windows.zip
```
