### ISSUE TITLE
allow_override flag does not work for assets

### ISSUE THREAD

**Issue by majkrzak** [meeDamian/github-release#2]
Updating the release fails when asset is beeing updated:

```yaml
    - uses: meeDamian/github-release@1.0
      with:
        token: ${{github.token}}
        commitish: ${{github.sha}}
        tag: latest
        name: Latest draft
        prerelease: true
        gzip: false
        files: >
          file.pdf:paper/paper.pdf
        allow_override: true
```

```
ERR: Uploading file.pdf to Github release has failed
{
  "message": "Validation Failed",
  "request_id": "07C0:5BBF:F7389:15503D:5D7E3EF4",
  "documentation_url": "https://developer.github.com/v3",
  "errors": [
    {
      "resource": "ReleaseAsset",
      "code": "already_exists",
      "field": "name"
    }
  ]
}
```

After manually removing the asset it seems that `tag` and `commitsh` was also not updated.
