### ISSUE TITLE
pass environment variables as file

### ISSUE THREAD

**Issue by adagrad** [meeDamian/github-release#22]
I am using the same action for different files. In order to not repeat myself too much, I use environmental variables. Hoever it seems that we can no use env variables in the files section.

```
  env:
    FILE: data/.test.csv
    ...
      - uses: meeDamian/github-release@2.0
        name: upload file
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          files: ${{ env.FILE }}
          gzip: false
          tag: 0.0.1
```

results in:

```
 Files to be uploaded to Github:
  {
    "message": "Not Found",
    "documentation_url": "https://docs.github.com/rest/reference/repos#delete-a-release-asset"
  }
  stat: can't stat '/github/home/assets/*': No such file or directory
  curl: Can't open '/github/home/assets/*'!
  curl: try 'curl --help' or 'curl --manual' for more information
  curl: (26) Failed to open/read local data from file/application
```
