### ISSUE TITLE
Unable to override assets on existing release

### ISSUE THREAD

**Issue by ReenigneArcher** [meeDamian/github-release#25]
Same issue as #2

```yml
        - name: Upload assets to release
          uses: meeDamian/github-release@2.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: latest
            name: latest
            allow_override: true
            gzip: false
            files: >
                filename1.ext
                filename2.ext
```

```txt
Create Release
Upload Assets
  Files to be uploaded to Github:
  filename1.ext
  filename2.ext
  {
    "message": "Not Found",
    "documentation_url": "https://docs.github.com/rest/reference/repos#delete-a-release-asset"
  }
  Error: failed to upload asset: filename1.ext (see log for details)
  
  	ERR: Failed asset upload: filename1.ext
  {
    "message": "Validation Failed",
    "request_id": "07C0:4CCE:385984:52E5BB:6120476B",
    "documentation_url": "https://docs.github.com/rest",
    "errors": [
      {
        "resource": "ReleaseAsset",
        "code": "already_exists",
        "field": "name"
      }
    ]
  }
```

I also tried with `uses: meeDamian/github-release@2.0.3`; however that fails to find the version.
```txt
Error: Unable to resolve action `meeDamian/github-release@2.0.3`, unable to find version `2.0.3`
```
