### ISSUE TITLE
does not trigger workflows with "on release" action

### ISSUE THREAD

**Issue by ReenigneArcher** [meeDamian/github-release#26]
I have a separate workflow with the following trigger:

```yml
on:
  release:
    types: [created, edited]
```

It does not trigger after running the workflow with your action, even when the release is created properly.
