### ISSUE TITLE
Allow variable usage for tag

### ISSUE THREAD

**Issue by cilerler** [meeDamian/github-release#3]
I want to provide a tag number via environment variable set in earlier steps; however, it treats it as a string.

```
tag: $buildNumber
```

then I came up with the workaround below

```
tag: buildNumber
```

_(I'm sorry, my shell scripting is not good enough, so I came up with something like this in [here]( https://github.com/meeDamian/github-release/blob/master/entrypoint.sh#L21))_

```sh
if [ ! -z "${TAG}" ]; then
  if TAGFROMENVVAR=$(printenv ${TAG}); then
    if [ ! -z "$TAGFROMENVVAR" ]; then
      TAG="${TAGFROMENVVAR}"
    fi
  fi
fi
```

it checks if the given name exists in an environment variable or not.

**Comment by meeDamian** [comment]
I agree that it's annoying vars aren't accepted by action inputs :(.

Using env vars indeed seems like the right approach.

**Comment by meeDamian** [comment]
I've added support for passing tags through an env var here: https://github.com/meeDamian/github-release/commit/ad87d288ffdf6d1179f0e3595c4d76d57ffd53ba .

You can test it now by (for now) running sth like:

```yml
steps:
  …

  - name: This step creates the tag name
    run: echo ::set-env name=GIT_TAG::"v1.0.0"

  - uses: meeDamian/github-release@ad87d28
    with:
      token: ${{secrets.GITHUB_TOKEN}}
  …
```

Please let me know if it works for you :).
