### ISSUE TITLE
Do globs work in `files`?

### ISSUE THREAD

**Issue by beyarkay** [meeDamian/github-release#34]
Hi!

Thanks for the project, really appreciate it.

Just wondering if globs work in files? for example will the following:

```yaml
jobs:
  build:
  ...
    steps:
    ...
    - uses: meeDamian/github-release@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        gzip: false
        allow_override: true
        files: build/*.txt
```

expand to upload every `*.txt` file under the `build/` directory individually?

I've tried look through the source code, but my bash isn't as good as I thought. There's [one comment](https://github.com/meeDamian/github-release/blob/master/entrypoint.sh#L167) that implies globbing does happen, but some small tests just in my shell make it seem like they don't work.

I think the following is the same as the source, but it doesn't glob, and echos `calendars/*.ics`

```sh
glob=build/*.txt
for filename in "$glob"; do
    echo $filename
done
```

However this example (which isn't the same) globs as expected:
```sh
for filename in build/*.txt; do
    echo $filename
done
```

If you can confirm what exactly the expected behaviour is, I'm happy to make a PR to add this feature!

Thanks!
